"""add user_id to baggage

Revision ID: 7bb1a003a7c0
Revises: d1d185f69a66
Create Date: 2025-01-30 18:02:35.115858

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7bb1a003a7c0'
down_revision = 'd1d185f69a66'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('baggage', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_baggage_user', 'user', ['user_id'], ['id'])  # Named Foreign Key
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('baggage', schema=None) as batch_op:
        batch_op.drop_constraint('fk_baggage_user', type_='foreignkey') # Drop the named foreign key
        batch_op.drop_column('user_id')